# Generated by Django 5.2.14 on 2026-05-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
    ]
