# Generated by Django 5.2.14 on 2026-05-18 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('zip', 'Zip'), ('pdf', 'PDF'), ('text', 'Text')], editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_key', models.CharField(max_length=20)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
