# Generated by Django 5.2.14 on 2026-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file',
            field=models.FileField(default='temporary_file', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
